[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "edit_mannings"
version = "1.0.0"
dependencies = [
"numpy >= 1.16.0"
]

[project.scripts]
edit-mannings = "edit_mannings.edit_mannings:main"
